settings:
  shulker-inventory: # Настройка системы поднятия предметов в шалкер
    black-list-items: [] # Список предметов, которые нельзя поднять в шалкер
    white-list-shulkers: # Список шалкеров, на которые данная механика распостраняется
      - BLACK_SHULKER_BOX
    message: # Настройка уведомления о поднятии предмета
      enabled: true # Включена ли данная функция
      period: 1s # Задержка, с которой сообщение будет отправляться
      message: "&6➤ &fПредмет &e{item} &fбыл добавлен в шалкер!" # Сообщение, которое будет отправляться
  shulker-open: # Настройка механики открытия шалкеров не устанавливая их
    enabled: true # Включена ли данная функция
    shulkers-list: # Список шалкеров, на которые данная механика распостраняется
      - BLACK_SHULKER_BOX

messages:
  fast-open-shulker:
    in-pvp: "&6➤ &fВы не можете открыть &6шалкер &fв режиме PvP"
    cant-click: "&6➤ &fНельзя перемещать &6шалкер&f, когда он открыт"